### ISSUE TITLE
No module named optimize

### ISSUE THREAD

**Issue by Yanxing-Shi** [Pearl-UTexas/POMDP-HD#3]
when I run 
```
python run_main.py
```
```
Traceback (most recent call last):
  File "run_main.py", line 7, in <module>
    from planner_interface import planner_interface
  File "/home/user/code/POMDP-HD/planner/planner_interface.py", line 5, in <module>
    from pomdp_hd_planner import *
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 22, in <module>
    from planner_core.src.trajOpt_snopt import *
  File "/home/user/code/POMDP-HD/planner/planner_core/src/trajOpt_snopt.py", line 13, in <module>
    from optimize import snopta, SNOPT_options
ImportError: No module named optimize
```
please help me out.

**Comment by jainajinkya** [comment]
Hi,
You would need to have Snopt 7 optimization package (https://web.stanford.edu/group/SOL/snopt.htm) installed. Also, you would need to install python interface for snopt (https://github.com/snopt/snopt-python/tree/snopt-only). If you don't have access to snopt package, alternatively, you can use the python optimization package from SciPy module. Script "planner_core/src/trajOpt.py" provides an interface to use scipy.optimize, however, you might need to import it in the main runfile.

**Comment by Yanxing-Shi** [comment]
Thank you very much for your help!
When I switched the ''USE_SNOPT = False'' in ''planner/pomdp_hd_planner.py''.But when i run 
```
python run_main.py
```
I have made these mistakes:
```
Set Goal = 0
0
GCs set
start_mu:  [50. 50.] 
start_cov: [[1150.    0.]
 [   0. 1150.]] 
goal:  [0. 0.]
Traceback (most recent call last):
  File "run_main.py", line 32, in <module>
    mu_plan, s_plan, u_plan = planner.generate_plan()
  File "/home/user/code/POMDP-HD/planner/planner_interface.py", line 67, in generate_plan
    mu_plan, s_plan, u_plan = self.planner.plan_optimal_path()
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 135, in plan_optimal_path
    self.find_set_of_ds_to_cs_goals()
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 364, in find_set_of_ds_to_cs_goals
    projected_goal = copy.copy(self.project_on_boundary(self.wts2ds(ds_goal), res.x))
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 429, in project_on_boundary
    projection = deepcopy(res)
NameError: global name 'deepcopy' is not defined
```
Please help me out.

**Comment by jainajinkya** [comment]
I think it's a bug in the code.  You need to add `from copy import deepcopy` at the start of the `pomdp_hd_planner.py` script. Once you verify it is working you can create a pull request to merge the changes to the master branch.

**Comment by Yanxing-Shi** [comment]
I follow your advice which works,but there is other error.
```
Traceback (most recent call last):
  File "run_main.py", line 32, in <module>
    mu_plan, s_plan, u_plan = planner.generate_plan()
  File "/home/user/code/POMDP-HD/planner/planner_interface.py", line 67, in generate_plan
    mu_plan, s_plan, u_plan = self.planner.plan_optimal_path()
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 137, in plan_optimal_path
    return self.find_optimal_path()  
  File "/home/user/code/POMDP-HD/planner/pomdp_hd_planner.py", line 148, in find_optimal_path
    cost, mu_plan, s_plan, u_plan, final_wts = self.opt.cs_optimize(self.start_mu, self.start_cov, self.belief.wts, self.t,  self.goal_cs)
AttributeError: trajectoryOptimization instance has no attribute 'cs_optimize'
```
